[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://millennium-choosing-victory-drawings.trycloudflare.com"
  NEXT_PUBLIC_BACKEND_WEBHOOK_URL = "https://millennium-choosing-victory-drawings.trycloudflare.com/webhooks/whatsapp"
